version: "3"
services:
  goobot_db:
    container_name: "goobot_db"
    image: "postgres:13.4"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - goobot:/home/bot/app

  goobot_app:
    container_name: "goobot_app"
    depends_on: 
      - "goobot_db"
    build: .
    environment:
      - POSTGRES_HOST=goobot_db
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - APP_KEY
      - BOTPREFIX
      - DEBUG
    ports:
      - "3000:3000"

volumes:
  goobot: