version: "3"
services:
  postgres:
    container_name: "vybot_database"
    image: "postgres:12"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    labels:
      NAME: "VybotDB"