version: "3"
services:
  postgres:
    container_name: "vybot_database"
    image: "postgres:12"
    environment:
      - POSTGRES_USER=vybot
      - POSTGRES_PASSWORD=vybot
      - POSTGRES_DB=vybot
    ports:
      - "5432:5432"
    labels:
      NAME: "VybotDB"