workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }} 
      - run:
          name: install
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test:ci
      - run:
          name: clean
          command: npm prune --production
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - ./bin
            - ./data
            - ./dist
            - ./docker-compose.yml
            - ./package.json

  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /home/circleci
      - add_ssh_keys
      - run: chown -R $USER:$USER /home/circleci/*/*
      - run: scp -r /home/circleci/bin deployment@134.122.106.23:/home/deployment/vybot
      - run: scp -r /home/circleci/data deployment@134.122.106.23:/home/deployment/vybot
      - run: scp -r /home/circleci/dist deployment@134.122.106.23:/home/deployment/vybot
      - run: scp /home/circleci/docker-compose.yml deployment@134.122.106.23:/home/deployment/vybot
      - run: scp /home/circleci/package.json deployment@134.122.106.23:/home/deployment/vybot
      - run: ssh deployment@134.122.106.23 "cd vybot; npm install --only=prod; npm run deploy";
      