workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }} 
      - run:
          name: install
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm run test:ci
